/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.meco.MainPages.Admin.SettingsPage;

import com.meco.MainPages.Admin.CustomerInfoPage.AdminCustomerInfoPage;
import com.meco.MainPages.Admin.HomePage.AdminHomePage;
import com.meco.MainPages.Admin.RoomsPage.AdminRoomsPage;

/**
 *
 * @author ashishkumar
 */
public class AdminSettingsPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomePage
     */
    public AdminSettingsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        adminHomeBtn = new javax.swing.JMenu();
        adminCustomerInfoPage = new javax.swing.JMenu();
        adminRoomsBtn = new javax.swing.JMenu();
        adminStaffBtn = new javax.swing.JMenu();
        adminSettingsBtn = new javax.swing.JMenu();
        refreshBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Admin Settings Page");

        adminHomeBtn.setText("Home");
        adminHomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminHomeBtnMouseClicked(evt);
            }
        });
        menuBar.add(adminHomeBtn);

        adminCustomerInfoPage.setText("Customer Info");
        adminCustomerInfoPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminCustomerInfoPageMouseClicked(evt);
            }
        });
        menuBar.add(adminCustomerInfoPage);

        adminRoomsBtn.setText("Rooms");
        adminRoomsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminRoomsBtnMouseClicked(evt);
            }
        });
        menuBar.add(adminRoomsBtn);

        adminStaffBtn.setText("Staff");
        adminStaffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminStaffBtnMouseClicked(evt);
            }
        });
        menuBar.add(adminStaffBtn);

        adminSettingsBtn.setText("Settings");
        adminSettingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminSettingsBtnMouseClicked(evt);
            }
        });
        menuBar.add(adminSettingsBtn);

        refreshBtn.setText("Refresh");
        refreshBtn.setMargin(new java.awt.Insets(0, 465, 0, 0));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        menuBar.add(refreshBtn);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel1)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel1)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminHomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminHomeBtnMouseClicked
        AdminHomePage admin_home_page = new AdminHomePage();
        admin_home_page.setVisible(true);
        admin_home_page.pack();
        admin_home_page.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_adminHomeBtnMouseClicked

    private void adminCustomerInfoPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminCustomerInfoPageMouseClicked
        AdminCustomerInfoPage admin_customer_info_page = new AdminCustomerInfoPage();
        admin_customer_info_page.setVisible(true);
        admin_customer_info_page.pack();
        admin_customer_info_page.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_adminCustomerInfoPageMouseClicked

    private void adminRoomsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminRoomsBtnMouseClicked
        AdminRoomsPage admin_rooms_page = new AdminRoomsPage();
        admin_rooms_page.setVisible(true);
        admin_rooms_page.pack();
        admin_rooms_page.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_adminRoomsBtnMouseClicked

    private void adminStaffBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminStaffBtnMouseClicked
        AdminRoomsPage admin_rooms_page = new AdminRoomsPage();
        admin_rooms_page.setVisible(true);
        admin_rooms_page.pack();
        admin_rooms_page.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_adminStaffBtnMouseClicked

    private void adminSettingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminSettingsBtnMouseClicked
        AdminSettingsPage admin_settings_page = new AdminSettingsPage();
        admin_settings_page.setVisible(true);
        admin_settings_page.pack();
        admin_settings_page.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_adminSettingsBtnMouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        AdminSettingsPage page = new AdminSettingsPage();
        page.setVisible(true);
        page.pack();
        page.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_refreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSettingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSettingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSettingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSettingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSettingsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminCustomerInfoPage;
    private javax.swing.JMenu adminHomeBtn;
    private javax.swing.JMenu adminRoomsBtn;
    private javax.swing.JMenu adminSettingsBtn;
    private javax.swing.JMenu adminStaffBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu refreshBtn;
    // End of variables declaration//GEN-END:variables
}
