/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.meco;
import java.awt.event.*;
import java.util.*;

import javax.swing.JButton;

/**
 *
 * @author ashishkumar
 */
public class Testing extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Testing
     */
    public Testing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        JButton btns[] = {jButton1, jButton2, jButton3, jButton4};
        for (int i = 0; i < 4; i++) {
            btns[i].setText("jButton" + String.valueOf(i));
            btns[i].setBackground(new java.awt.Color(219, 35, 31));
            btns[i].addActionListener(actionListener);
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // jButton1.setText("jButton1");
        // jButton1.setBackground(new java.awt.Color(219, 35, 31));
        // jButton1.addActionListener(actionListener);

        // jButton2.setText("jButton2");
        // jButton2.setBackground(new java.awt.Color(219, 35, 31));
        // jButton2.addActionListener(actionListener);

        // jButton3.setText("jButton3");
        // jButton3.setBackground(new java.awt.Color(219, 35, 31));
        // jButton3.addActionListener(actionListener);

        // jButton4.setText("jButton4");
        // jButton4.setBackground(new java.awt.Color(219, 35, 31));
        // jButton4.addActionListener(actionListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Testing().setVisible(true);
            }
        });
    }

    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    Map<String, Integer> btnMap = Testing2.btnStates();

    ActionListener actionListener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            JButton btn = (JButton) e.getSource();
            String btnName = btn.getText();
            int btnState = btnMap.get(btnName);

            if (btnState == 0) {
                btn.setBackground(new java.awt.Color(31, 219, 53)); // Green background color
                btnState++;
                btnMap.put(btnName, btnState);
            } else if (btnState == 1) {
                btn.setBackground(new java.awt.Color(34, 31, 219)); // Blue background color
                btnState++;
                btnMap.put(btnName, btnState);
            }  else if (btnState == 2) {
                btn.setBackground(new java.awt.Color(219, 35, 31)); // Red background color
                btnState *= 0;
                btnMap.put(btnName, btnState);
            }
            System.out.println("---------------------------------------------------------------");
            System.out.println(btnMap);
            System.out.println(btnState);
        }
    };
    @Override
    public void actionPerformed(ActionEvent e) {}
}

// public void actionPerformed(ActionEvent e) {
//     String btnState = (String)e.getSource() + "State";
//     javax.swing.JButton b = (javax.swing.JButton) e.getSource();
//     if (btnState.equals("0")) {b.setBackground(new java.awt.Color(219, 35, 31));}
//     else if (btnState.equals("1")) {b.setBackground(new java.awt.Color(31, 219, 53));}
//     else if (btnState.equals("2")) {b.setBackground(new java.awt.Color(34, 31, 219));}
// }