/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.meco.LoginSignup;

import com.meco.DB.DB;
import com.meco.MainPages.Admin.HomePage.AdminHomePage;
import com.meco.MainPages.Developer.DeveloperPage;
import com.meco.MainPages.Staff.StaffPage;
import com.meco.MainPages.User.UserPage;

import javax.swing.JOptionPane;

/**
 *
 * @author ashishkumar
 */
public class SignupPage extends javax.swing.JFrame {

    /**
     * Creates new form SignupPage
     */
    public SignupPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordField1 = new javax.swing.JPasswordField();
        welcomeLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        confirmPasswordLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        signupAsLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        signupBtn = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();
        signupAsField = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();

        passwordField1.setBackground(new java.awt.Color(217, 217, 217));
        passwordField1.setText("Enter your password");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        welcomeLabel.setFont(new java.awt.Font("AppleGothic", 1, 36)); // NOI18N
        welcomeLabel.setText("Welcome! Create a new Account.");

        emailLabel.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        emailLabel.setText("Email");

        emailField.setBackground(new java.awt.Color(217, 217, 217));
        emailField.setText("Enter your email ID");
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        nameLabel.setText("Name");

        nameField.setBackground(new java.awt.Color(217, 217, 217));
        nameField.setText("Enter your name");
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFieldFocusLost(evt);
            }
        });

        confirmPasswordLabel.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        confirmPasswordLabel.setText("Confirm Password");

        passwordLabel.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        passwordLabel.setText("Password");

        ageField.setBackground(new java.awt.Color(217, 217, 217));
        ageField.setText("Enter your age");
        ageField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFieldFocusLost(evt);
            }
        });

        signupAsLabel.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        signupAsLabel.setText("Sign Up As");

        ageLabel.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        ageLabel.setText("Age");

        signupBtn.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        signupBtn.setText("SIGNUP");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        passwordField.setBackground(new java.awt.Color(217, 217, 217));
        passwordField.setText("Enter your password");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });

        confirmPasswordField.setBackground(new java.awt.Color(217, 217, 217));
        confirmPasswordField.setText("Confirm your password");
        confirmPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPasswordFieldFocusLost(evt);
            }
        });

        signupAsField.setBackground(new java.awt.Color(217, 217, 217));
        signupAsField.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        signupAsField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User", "Staff", "Developer" }));

        backButton.setFont(new java.awt.Font("AppleGothic", 1, 24)); // NOI18N
        backButton.setText("<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLabel))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(passwordLabel)
                                        .addGap(309, 309, 309))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(passwordField)
                                        .addGap(99, 99, 99)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmPasswordLabel)
                                    .addComponent(confirmPasswordField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageLabel))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(signupAsLabel)
                                    .addComponent(signupAsField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(welcomeLabel)
                        .addGap(44, 44, 44)))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordLabel)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupAsLabel)
                    .addComponent(ageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupAsField))
                .addGap(29, 29, 29)
                .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        setVisible(true);
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        String name = nameField.getText();
        String email = emailField.getText();
        String password = String.valueOf(passwordField.getPassword());
        String confirm_password = String.valueOf(confirmPasswordField.getPassword());
        String age = ageField.getText();
        String login_as = signupAsField.getSelectedItem().toString();

        // safety checks for entering the data in the database
        if (name.equals(null) || name.equals("Enter your name")) {
            JOptionPane.showMessageDialog(null, "Enter a valid name!", "Invalid Input", 2);
        } else if (email.equals(null) || email.equals("Enter your email ID")) {
            JOptionPane.showMessageDialog(null, "Enter a valid email ID!", "Invalid Input", 2);
        } else if (password.equals(null) || password.equals("Enter your password")) {
            JOptionPane.showMessageDialog(null, "Enter a valid password!", "Invalid Input", 2);
        } else if (confirm_password.equals(null) || confirm_password.equals("Confirm your password")) {
            JOptionPane.showMessageDialog(null, "Confirm your password!", "Invalid Input", 2);
        } else if (!confirm_password.equals(password)) {
            JOptionPane.showMessageDialog(null, "Confirm Password is not same as your password!", "Invalid Input", 2);
        } else if (age.equals(null) || age.equals("Enter your age")) {
            JOptionPane.showMessageDialog(null, "Enter a valid age!", "Invalid Input", 2);
        } else if (Integer.parseInt(age) < 0 || Integer.parseInt(age) > 100) {
            JOptionPane.showMessageDialog(null, "Enter a valid age!", "Invalid Input", 2);
        } else {
            if (DB.addSignupData(name, email, password, confirm_password, Integer.parseInt(age), login_as)) { // if true is returned
                openWindow(login_as);
                this.dispose();
            }
        }
    }//GEN-LAST:event_signupBtnActionPerformed

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        if (nameField.getText().equals("Enter your name")) {
            nameField.setText("");
        }
    }//GEN-LAST:event_nameFieldFocusGained

    private void nameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusLost
        if (nameField.getText().equals("") || nameField.getText().equals("Enter your name")) {
            nameField.setText("Enter your name");
        }
    }//GEN-LAST:event_nameFieldFocusLost

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        if (emailField.getText().equals("Enter your email ID")) {
            emailField.setText("");
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        if (emailField.getText().equals("") || emailField.getText().equals("Enter your email ID")) {
            emailField.setText("Enter your email ID");
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        if (String.valueOf(passwordField.getPassword()).equals("Enter your password")) {
            passwordField.setText("");
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if (String.valueOf(passwordField.getPassword()).equals("") || String.valueOf(passwordField.getPassword()).equals("Enter your password")) {
            passwordField.setText("Enter your password");
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    private void confirmPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordFieldFocusGained
        if (String.valueOf(confirmPasswordField.getPassword()).equals("Confirm your password")) {
            confirmPasswordField.setText("");
        }
    }//GEN-LAST:event_confirmPasswordFieldFocusGained

    private void confirmPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordFieldFocusLost
        if (String.valueOf(confirmPasswordField.getPassword()).equals("") || String.valueOf(confirmPasswordField.getPassword()).equals("Confirm your password")) {
            confirmPasswordField.setText("Confirm your password");
        }
    }//GEN-LAST:event_confirmPasswordFieldFocusLost

    private void ageFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFieldFocusGained
        if (ageField.getText().equals("Enter your age")) {
            ageField.setText("");
        }
    }//GEN-LAST:event_ageFieldFocusGained

    private void ageFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFieldFocusLost
        if (ageField.getText().equals("") || ageField.getText().equals("Enter your age")) {
            ageField.setText("Enter your age");
        }
    }//GEN-LAST:event_ageFieldFocusLost

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        LoginPage login_page = new LoginPage();
        login_page.setVisible(true);
        login_page.toFront();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SignupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JComboBox<String> signupAsField;
    private javax.swing.JLabel signupAsLabel;
    private javax.swing.JButton signupBtn;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
    public static void openWindow(String WindowName) {
        if (WindowName.equals("Admin")) {
            AdminHomePage window = new AdminHomePage();
            window.setVisible(true);
            window.pack();
            window.setLocationRelativeTo(null);
        } else if (WindowName.equals("User")) {
            UserPage window = new UserPage();
            window.setVisible(true);
            window.pack();
            window.setLocationRelativeTo(null);
        } else if (WindowName.equals("Staff")) {
            StaffPage window = new StaffPage();
            window.setVisible(true);
            window.pack();
            window.setLocationRelativeTo(null);
        } else if (WindowName.equals("Developer")) {
            DeveloperPage window = new DeveloperPage();
            window.setVisible(true);
            window.pack();
            window.setLocationRelativeTo(null);
        } else {
            System.out.println("no such window found");
        }
    }
}