/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.meco.MainPages.Admin.RoomsPage;

import java.awt.event.*;
import java.sql.SQLException;
import java.util.*;

import javax.swing.JButton;

import com.meco.DB.DB;
import com.meco.MainPages.Admin.adminUtils;
import com.meco.MainPages.Admin.CustomerInfoPage.AdminCustomerInfoPage;
import com.meco.MainPages.Admin.HomePage.AdminHomePage;
import com.meco.MainPages.Admin.SettingsPage.AdminSettingsPage;
import com.meco.MainPages.Admin.StaffPage.AdminStaffPage;

/**
 *
 * @author ashishkumar
 */
public class AdminRoomsPage extends javax.swing.JFrame {

	/**
	 * Creates new form AdminHomePage
	 */
	public AdminRoomsPage() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		btn102 = new javax.swing.JButton();
		btn101 = new javax.swing.JButton();
		btn103 = new javax.swing.JButton();
		btn104 = new javax.swing.JButton();
		btn105 = new javax.swing.JButton();
		btn106 = new javax.swing.JButton();
		btn107 = new javax.swing.JButton();
		btn108 = new javax.swing.JButton();
		btn109 = new javax.swing.JButton();
		btn110 = new javax.swing.JButton();
		btn207 = new javax.swing.JButton();
		btn208 = new javax.swing.JButton();
		btn209 = new javax.swing.JButton();
		btn210 = new javax.swing.JButton();
		btn202 = new javax.swing.JButton();
		btn201 = new javax.swing.JButton();
		btn203 = new javax.swing.JButton();
		btn204 = new javax.swing.JButton();
		btn205 = new javax.swing.JButton();
		btn206 = new javax.swing.JButton();
		btn409 = new javax.swing.JButton();
		btn303 = new javax.swing.JButton();
		btn410 = new javax.swing.JButton();
		btn304 = new javax.swing.JButton();
		btn402 = new javax.swing.JButton();
		btn305 = new javax.swing.JButton();
		btn401 = new javax.swing.JButton();
		btn306 = new javax.swing.JButton();
		btn403 = new javax.swing.JButton();
		btn307 = new javax.swing.JButton();
		btn404 = new javax.swing.JButton();
		btn308 = new javax.swing.JButton();
		btn405 = new javax.swing.JButton();
		btn309 = new javax.swing.JButton();
		btn406 = new javax.swing.JButton();
		btn310 = new javax.swing.JButton();
		btn302 = new javax.swing.JButton();
		btn407 = new javax.swing.JButton();
		btn408 = new javax.swing.JButton();
		btn301 = new javax.swing.JButton();
		btn805 = new javax.swing.JButton();
		btn709 = new javax.swing.JButton();
		btn609 = new javax.swing.JButton();
		btn806 = new javax.swing.JButton();
		btn610 = new javax.swing.JButton();
		btn710 = new javax.swing.JButton();
		btn602 = new javax.swing.JButton();
		btn702 = new javax.swing.JButton();
		btn601 = new javax.swing.JButton();
		btn807 = new javax.swing.JButton();
		btn603 = new javax.swing.JButton();
		btn808 = new javax.swing.JButton();
		btn604 = new javax.swing.JButton();
		btn701 = new javax.swing.JButton();
		btn605 = new javax.swing.JButton();
		btn606 = new javax.swing.JButton();
		btn809 = new javax.swing.JButton();
		btn502 = new javax.swing.JButton();
		btn703 = new javax.swing.JButton();
		btn501 = new javax.swing.JButton();
		btn810 = new javax.swing.JButton();
		btn704 = new javax.swing.JButton();
		btn503 = new javax.swing.JButton();
		btn802 = new javax.swing.JButton();
		btn504 = new javax.swing.JButton();
		btn705 = new javax.swing.JButton();
		btn505 = new javax.swing.JButton();
		btn801 = new javax.swing.JButton();
		btn506 = new javax.swing.JButton();
		btn706 = new javax.swing.JButton();
		btn507 = new javax.swing.JButton();
		btn803 = new javax.swing.JButton();
		btn508 = new javax.swing.JButton();
		btn707 = new javax.swing.JButton();
		btn509 = new javax.swing.JButton();
		btn804 = new javax.swing.JButton();
		btn510 = new javax.swing.JButton();
		btn708 = new javax.swing.JButton();
		displayGreenBtn = new javax.swing.JButton();
		btn607 = new javax.swing.JButton();
		btn608 = new javax.swing.JButton();
		roomIsAvilableLabel = new javax.swing.JLabel();
		roomIsBookedLabel = new javax.swing.JLabel();
		displayRedBtn = new javax.swing.JButton();
		underMaintainanceLabel = new javax.swing.JLabel();
		displayBlueBtn = new javax.swing.JButton();
		menuBar = new javax.swing.JMenuBar();
		adminHomeBtn = new javax.swing.JMenu();
		adminCustomerInfoPage = new javax.swing.JMenu();
		adminRoomsBtn = new javax.swing.JMenu();
		adminStaffBtn = new javax.swing.JMenu();
		adminSettingsBtn = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		JButton btns[] = {
				btn101, btn102, btn103, btn104, btn105, btn106, btn107, btn108, btn109, btn110,
				btn201, btn202, btn203, btn204, btn205, btn206, btn207, btn208, btn209, btn210,
				btn301, btn302, btn303, btn304, btn305, btn306, btn307, btn308, btn309, btn310,
				btn401, btn402, btn403, btn404, btn405, btn406, btn407, btn408, btn409, btn410,
				btn501, btn502, btn503, btn504, btn505, btn506, btn507, btn508, btn509, btn510,
				btn601, btn602, btn603, btn604, btn605, btn606, btn607, btn608, btn609, btn610,
				btn701, btn702, btn703, btn704, btn705, btn706, btn707, btn708, btn709, btn710,
				btn801, btn802, btn803, btn804, btn805, btn806, btn807, btn808, btn809, btn810
		};

		int roomNums[] = new int[80];
		int part1 = 100;
		int part2 = 1;
		for (int i = 0; i < roomNums.length; i++) {
			int num = part1 + part2;
			if (num % 10 == 0) {
				roomNums[i] = num;
				part2 = 0;
				part1 += 100;
			} else {
				roomNums[i] = num;
			}
			part2++;
		}

		for (int i = 0; i < 80; i++) {
			JButton btn = (JButton) btns[i];
			btn.setBackground(new java.awt.Color(255, 255, 255));
			btn.setFont(new java.awt.Font("AppleGothic", 0, 10)); // NOI18N
			btn.setText(String.valueOf(roomNums[i]));
			btn.setFocusPainted(false);
			btn.setMaximumSize(new java.awt.Dimension(70, 70));
			btn.setMinimumSize(new java.awt.Dimension(70, 70));
			btn.addActionListener(actionListener);
		}

		roomIsAvilableLabel.setFont(new java.awt.Font("AppleGothic", 0, 10)); // NOI18N
		roomIsAvilableLabel.setText("Room is Available");
		roomIsAvilableLabel.setMaximumSize(new java.awt.Dimension(81, 20));
		roomIsAvilableLabel.setMinimumSize(new java.awt.Dimension(81, 20));
		roomIsAvilableLabel.setPreferredSize(new java.awt.Dimension(81, 20));

		roomIsBookedLabel.setFont(new java.awt.Font("AppleGothic", 0, 10)); // NOI18N
		roomIsBookedLabel.setText("Room is Booked");
		roomIsBookedLabel.setMaximumSize(new java.awt.Dimension(73, 20));
		roomIsBookedLabel.setMinimumSize(new java.awt.Dimension(73, 20));
		roomIsBookedLabel.setPreferredSize(new java.awt.Dimension(73, 20));

		displayGreenBtn.setBackground(new java.awt.Color(51, 255, 0));
		displayGreenBtn.setFont(new java.awt.Font("AppleGothic", 0, 10)); // NOI18N
		displayGreenBtn.setFocusPainted(false);
		displayGreenBtn.setPreferredSize(new java.awt.Dimension(18, 20));

		displayRedBtn.setBackground(new java.awt.Color(255, 51, 51));
		displayRedBtn.setFont(new java.awt.Font("AppleGothic", 0, 10)); // NOI18N
		displayRedBtn.setFocusPainted(false);
		displayRedBtn.setMaximumSize(new java.awt.Dimension(18, 20));
		displayRedBtn.setMinimumSize(new java.awt.Dimension(18, 20));
		displayRedBtn.setPreferredSize(new java.awt.Dimension(18, 20));

		underMaintainanceLabel.setFont(new java.awt.Font("AppleGothic", 0, 10)); // NOI18N
		underMaintainanceLabel.setText("Under Maintainance");
		underMaintainanceLabel.setMaximumSize(new java.awt.Dimension(92, 20));
		underMaintainanceLabel.setMinimumSize(new java.awt.Dimension(92, 20));
		underMaintainanceLabel.setPreferredSize(new java.awt.Dimension(92, 20));

		displayBlueBtn.setBackground(new java.awt.Color(0, 51, 255));
		displayBlueBtn.setFont(new java.awt.Font("AppleGothic", 0, 10)); // NOI18N
		displayBlueBtn.setFocusPainted(false);

		adminHomeBtn.setText("Home");
		adminHomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				adminHomeBtnMouseClicked(evt);
			}
		});
		menuBar.add(adminHomeBtn);

		adminCustomerInfoPage.setText("Customer Info");
		adminCustomerInfoPage.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				adminCustomerInfoPageMouseClicked(evt);
			}
		});
		menuBar.add(adminCustomerInfoPage);

		adminRoomsBtn.setText("Rooms");
		adminRoomsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				adminRoomsBtnMouseClicked(evt);
			}
		});
		menuBar.add(adminRoomsBtn);

		adminStaffBtn.setText("Staff");
		adminStaffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				adminStaffBtnMouseClicked(evt);
			}
		});
		menuBar.add(adminStaffBtn);

		adminSettingsBtn.setText("Settings");
		adminSettingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				adminSettingsBtnMouseClicked(evt);
			}
		});
		menuBar.add(adminSettingsBtn);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(btn401,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn402,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn403,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn404,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn405,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn406,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn407,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn408,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn409,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn410,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(btn501,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn502,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn503,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn504,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn505,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn506,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn507,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn508,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn509,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn510,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(btn601,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn602,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn603,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn604,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn605,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn606,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn607,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn608,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn609,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn610,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(btn701,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn702,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn703,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn704,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn705,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn706,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn707,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn708,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn709,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn710,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(btn801,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn802,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn803,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn804,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn805,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn806,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn807,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn808,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn809,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btn810,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														50,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addComponent(btn101,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn102,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn103,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn104,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn105,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn106,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn107,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn108,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn109,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn110,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup()
																.addComponent(btn301,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn302,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn303,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn304,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn305,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn306,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn307,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn308,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn309,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn310,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup()
																.addComponent(btn201,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn202,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn203,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn204,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn205,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn206,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn207,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn208,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn209,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btn210,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGap(48, 48, 48)
												.addGroup(layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(displayGreenBtn,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																30,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(displayRedBtn,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(displayBlueBtn,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																0,
																Short.MAX_VALUE))
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(roomIsAvilableLabel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(roomIsBookedLabel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(underMaintainanceLabel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGap(48, 64, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGap(33, 33, 33)
												.addGroup(layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(displayGreenBtn,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(roomIsAvilableLabel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(displayRedBtn,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(roomIsBookedLabel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(displayBlueBtn,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(underMaintainanceLabel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
												.addGap(111, 111, 111))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												layout
														.createSequentialGroup()
														.addGap(16, 16, 16)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(btn101,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn102,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn103,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn104,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn105,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn106,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn107,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn108,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn109,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn110,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(btn201,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn202,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn203,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn204,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn205,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn206,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn207,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn208,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn209,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn210,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(btn301,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn302,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn303,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn304,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn305,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn306,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn307,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn308,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn309,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn310,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(btn401,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn402,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn403,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn404,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn405,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn406,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn407,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn408,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn409,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(btn410,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btn501,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn502,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn503,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn504,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn505,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn506,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn507,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn508,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn509,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn510,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btn601,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn602,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn603,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn604,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn605,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn606,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn607,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn608,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn609,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn610,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btn701,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn702,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn703,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn704,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn705,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn706,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn707,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn708,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn709,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn710,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btn801,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn802,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn803,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn804,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn805,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn806,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn807,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn808,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn809,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btn810,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(20, Short.MAX_VALUE)));
		setVisible(true);
		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void adminHomeBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_adminHomeBtnMouseClicked
		AdminHomePage admin_home_page = new AdminHomePage();
		admin_home_page.setVisible(true);
		admin_home_page.pack();
		admin_home_page.setLocationRelativeTo(null);
		this.dispose();
	}// GEN-LAST:event_adminHomeBtnMouseClicked

	private void adminCustomerInfoPageMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_adminCustomerInfoPageMouseClicked
		AdminCustomerInfoPage admin_customer_info_page = new AdminCustomerInfoPage();
		admin_customer_info_page.setVisible(true);
		admin_customer_info_page.pack();
		admin_customer_info_page.setLocationRelativeTo(null);
		this.dispose();
	}// GEN-LAST:event_adminCustomerInfoPageMouseClicked

	private void adminRoomsBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_adminRoomsBtnMouseClicked
		AdminRoomsPage admin_rooms_page = new AdminRoomsPage();
		admin_rooms_page.setVisible(true);
		admin_rooms_page.pack();
		admin_rooms_page.setLocationRelativeTo(null);
		this.dispose();
	}// GEN-LAST:event_adminRoomsBtnMouseClicked

	private void adminStaffBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_adminStaffBtnMouseClicked
		AdminStaffPage admin_staff_page = new AdminStaffPage();
		admin_staff_page.setVisible(true);
		admin_staff_page.pack();
		admin_staff_page.setLocationRelativeTo(null);
		this.dispose();
	}// GEN-LAST:event_adminStaffBtnMouseClicked

	private void adminSettingsBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_adminSettingsBtnMouseClicked
		AdminSettingsPage admin_settings_page = new AdminSettingsPage();
		admin_settings_page.setVisible(true);
		admin_settings_page.pack();
		admin_settings_page.setLocationRelativeTo(null);
		this.dispose();
	}// GEN-LAST:event_adminSettingsBtnMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel.
		 * For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AdminRoomsPage.class.getName()).log(
					java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AdminRoomsPage.class.getName()).log(
					java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AdminRoomsPage.class.getName()).log(
					java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AdminRoomsPage.class.getName()).log(
					java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminRoomsPage().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenu adminCustomerInfoPage;
	private javax.swing.JMenu adminHomeBtn;
	private javax.swing.JMenu adminRoomsBtn;
	private javax.swing.JMenu adminSettingsBtn;
	private javax.swing.JMenu adminStaffBtn;
	private javax.swing.JButton btn101;
	private javax.swing.JButton btn102;
	private javax.swing.JButton btn103;
	private javax.swing.JButton btn104;
	private javax.swing.JButton btn105;
	private javax.swing.JButton btn106;
	private javax.swing.JButton btn107;
	private javax.swing.JButton btn108;
	private javax.swing.JButton btn109;
	private javax.swing.JButton btn110;
	private javax.swing.JButton btn201;
	private javax.swing.JButton btn202;
	private javax.swing.JButton btn203;
	private javax.swing.JButton btn204;
	private javax.swing.JButton btn205;
	private javax.swing.JButton btn206;
	private javax.swing.JButton btn207;
	private javax.swing.JButton btn208;
	private javax.swing.JButton btn209;
	private javax.swing.JButton btn210;
	private javax.swing.JButton btn301;
	private javax.swing.JButton btn302;
	private javax.swing.JButton btn303;
	private javax.swing.JButton btn304;
	private javax.swing.JButton btn305;
	private javax.swing.JButton btn306;
	private javax.swing.JButton btn307;
	private javax.swing.JButton btn308;
	private javax.swing.JButton btn309;
	private javax.swing.JButton btn310;
	private javax.swing.JButton btn401;
	private javax.swing.JButton btn402;
	private javax.swing.JButton btn403;
	private javax.swing.JButton btn404;
	private javax.swing.JButton btn405;
	private javax.swing.JButton btn406;
	private javax.swing.JButton btn407;
	private javax.swing.JButton btn408;
	private javax.swing.JButton btn409;
	private javax.swing.JButton btn410;
	private javax.swing.JButton btn501;
	private javax.swing.JButton btn502;
	private javax.swing.JButton btn503;
	private javax.swing.JButton btn504;
	private javax.swing.JButton btn505;
	private javax.swing.JButton btn506;
	private javax.swing.JButton btn507;
	private javax.swing.JButton btn508;
	private javax.swing.JButton btn509;
	private javax.swing.JButton btn510;
	private javax.swing.JButton btn601;
	private javax.swing.JButton btn602;
	private javax.swing.JButton btn603;
	private javax.swing.JButton btn604;
	private javax.swing.JButton btn605;
	private javax.swing.JButton btn606;
	private javax.swing.JButton btn607;
	private javax.swing.JButton btn608;
	private javax.swing.JButton btn609;
	private javax.swing.JButton btn610;
	private javax.swing.JButton btn701;
	private javax.swing.JButton btn702;
	private javax.swing.JButton btn703;
	private javax.swing.JButton btn704;
	private javax.swing.JButton btn705;
	private javax.swing.JButton btn706;
	private javax.swing.JButton btn707;
	private javax.swing.JButton btn708;
	private javax.swing.JButton btn709;
	private javax.swing.JButton btn710;
	private javax.swing.JButton btn801;
	private javax.swing.JButton btn802;
	private javax.swing.JButton btn803;
	private javax.swing.JButton btn804;
	private javax.swing.JButton btn805;
	private javax.swing.JButton btn806;
	private javax.swing.JButton btn807;
	private javax.swing.JButton btn808;
	private javax.swing.JButton btn809;
	private javax.swing.JButton btn810;
	private javax.swing.JButton displayGreenBtn;
	private javax.swing.JButton displayRedBtn;
	private javax.swing.JButton displayBlueBtn;
	private javax.swing.JLabel roomIsAvilableLabel;
	private javax.swing.JLabel roomIsBookedLabel;
	private javax.swing.JLabel underMaintainanceLabel;
	private javax.swing.JMenuBar menuBar;
	public static JButton roomButton;
	Map<String, Integer> btnMap = adminUtils.getBtnStates();
	// End of variables declaration//GEN-END:variables

	ActionListener actionListener = new ActionListener() {
		@Override
		public void actionPerformed(ActionEvent e) {
			roomButton = (JButton) e.getSource();
			AdminRoomsPopup popup = new AdminRoomsPopup(); // open popup
			popup.setVisible(true);
			popup.setLocationRelativeTo(null);
		}
	};
}
