/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.meco.MainPages.Admin.RoomsPage;

import java.sql.Date;

import javax.swing.JButton;
import javax.swing.JOptionPane;

import com.meco.DB.DB;
import com.meco.MainPages.Admin.adminUtils;

/**
 *
 * @author ashishkumar
 */
public class checkInCustomer extends javax.swing.JFrame {

    /**
     * Creates new form checkInCustomer
     */
    public checkInCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ac_nonAcBtnGroup = new javax.swing.ButtonGroup();
        single_doubleBedBtnGroup = new javax.swing.ButtonGroup();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        bookRoomBtn = new javax.swing.JButton();
        ageLabel = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        phoneNoLabel = new javax.swing.JLabel();
        phoneNoField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        roomNoLabel = new javax.swing.JLabel();
        roomDetailsLabel = new javax.swing.JLabel();
        roomNoField = new javax.swing.JTextField();
        mealComboRadioBtn = new javax.swing.JRadioButton();
        singleBedRadioBtn = new javax.swing.JRadioButton();
        acRadioBtn = new javax.swing.JRadioButton();
        nonAcRadioBtn = new javax.swing.JRadioButton();
        doubleBedRadioBtn = new javax.swing.JRadioButton();
        checkInLabel = new javax.swing.JLabel();
        checkOutLabel = new javax.swing.JLabel();
        checkOutField = new javax.swing.JTextField();
        checkInField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emailField.setText("Enter email ID");
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        emailLabel.setText("Email");

        nameField.setText("Enter name");
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFieldFocusLost(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        nameLabel.setText("Name");

        titleLabel.setFont(new java.awt.Font("AppleGothic", 1, 48)); // NOI18N
        titleLabel.setText("Book a Room for the Customer!");

        bookRoomBtn.setBackground(new java.awt.Color(255, 255, 255));
        bookRoomBtn.setText("Book Room");
        bookRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomBtnActionPerformed(evt);
            }
        });

        ageLabel.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        ageLabel.setText("Age");

        ageField.setText("Enter age");
        ageField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFieldFocusLost(evt);
            }
        });

        phoneNoLabel.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        phoneNoLabel.setText("Phone No.");

        phoneNoField.setText("Enter Phone No.");
        phoneNoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNoFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneNoFieldFocusLost(evt);
            }
        });

        addressLabel.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        addressLabel.setText("Address");

        addressField.setText("Enter address");
        addressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFieldFocusLost(evt);
            }
        });

        roomNoLabel.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        roomNoLabel.setText("Room No.");

        roomDetailsLabel.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        roomDetailsLabel.setText("Room Details");

        mealComboRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        mealComboRadioBtn.setText("Meal Combo");

        singleBedRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        singleBedRadioBtn.setText("Single Bed");

        acRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        acRadioBtn.setText("AC Room");

        nonAcRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        nonAcRadioBtn.setText("Non-AC Room");

        doubleBedRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        doubleBedRadioBtn.setText("Double Bed");

        checkInLabel.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        checkInLabel.setText("Check-In Date");

        checkOutLabel.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        checkOutLabel.setText("Check-Out Date");

        ac_nonAcBtnGroup.add(acRadioBtn);
        ac_nonAcBtnGroup.add(nonAcRadioBtn);

        single_doubleBedBtnGroup.add(singleBedRadioBtn);
        single_doubleBedBtnGroup.add(doubleBedRadioBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageLabel)
                                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressLabel)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLabel)
                                    .addComponent(phoneNoLabel)
                                    .addComponent(phoneNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(bookRoomBtn))
                            .addComponent(roomDetailsLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mealComboRadioBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(roomNoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(roomNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(acRadioBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nonAcRadioBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(singleBedRadioBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(doubleBedRadioBtn)))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkOutLabel)
                                    .addComponent(checkInLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkOutField)
                                    .addComponent(checkInField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(addressField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(titleLabel)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(phoneNoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(roomDetailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomNoLabel)
                            .addComponent(roomNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(mealComboRadioBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acRadioBtn)
                            .addComponent(nonAcRadioBtn)
                            .addComponent(checkInLabel)
                            .addComponent(checkInField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(singleBedRadioBtn)
                            .addComponent(doubleBedRadioBtn)
                            .addComponent(checkOutLabel)
                            .addComponent(checkOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        setVisible(true);
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomBtnActionPerformed
        // creating all variables for the values received from the form
        String name = nameField.getText();
        String email = emailField.getText();
        String age = ageField.getText();
        String phoneNo =  phoneNoField.getText();
        String address = addressField.getText();
        int roomNo = Integer.parseInt(roomNoField.getText());

        boolean validRoomNumber = false;
        for (int i : adminUtils.getRoomNumbers()) {
            if (i == roomNo) { validRoomNumber = true; break; } // returns true only if room number is in the array
        }
        int roomStatus = adminUtils.getBtnStates().get("btn".concat(String.valueOf(roomNo))); // getting the status of the room

        // get the value of ac or non ac room field from the radio buttonGroup
        String ac_nonAcRoom = null;
        if (acRadioBtn.isSelected()) ac_nonAcRoom = "AC Rooom";
        else if (nonAcRadioBtn.isSelected()) ac_nonAcRoom = "Non-AC Rooom";
        else ac_nonAcRoom = "No input provided";

        // get the value of single or double bed field from the radio buttonGroup
        String single_doubleBedRoom = null;
        if (singleBedRadioBtn.isSelected()) single_doubleBedRoom = "Single-Bed Room";
        else if (doubleBedRadioBtn.isSelected()) single_doubleBedRoom = "Double-Bed Room";
        else single_doubleBedRoom = "No input provided";

        // get the value of the meal combo radio button
        String mealCombo = null;
        if (mealComboRadioBtn.isSelected()) mealCombo = "Meal Combo";
        else mealCombo = "No Meal Combo";

        String checkInDate = checkInField.getText();
        String checkOutDate = checkOutField.getText();


        // safety checks for entering the data in the database
        // if (name.equals(null) || name.equals("Enter name")) {
        //     JOptionPane.showMessageDialog(null, "Enter a valid name!", "Invalid Input", 2);
        // } else if (email.equals(null) || email.equals("Enter email ID")) {
        //     JOptionPane.showMessageDialog(null, "Enter a valid email ID!", "Invalid Input", 2);
        // } else if (age.equals(null) || age.equals("Enter age")) {
        //     JOptionPane.showMessageDialog(null, "Enter a valid age!", "Invalid Input", 2);
        // } else if (Integer.parseInt(age) < 0 || Integer.parseInt(age) > 100) {
        //     JOptionPane.showMessageDialog(null, "Enter a valid age!", "Invalid Input", 2);
        // } else if (phoneNo.equals(null) || phoneNo.equals("Enter Phone No.") || phoneNo.length() < 10) {
        //     JOptionPane.showMessageDialog(null, "Enter a valid phone number!", "Invalid Input", 2);
        // } else if (address.equals(null) || address.equals("Enter address")) {
        //     JOptionPane.showMessageDialog(null, "Enter a valid address!", "Invalid Input", 2);
        // } else if (!validRoomNumber || roomStatus != 0 || !String.valueOf(roomNo).equals(AdminRoomsPage.roomButton.getText())) { // roomStatus == 0 means room is available
        //     JOptionPane.showMessageDialog(null, "Invalid Room Number!", "Invalid Input", 2);
        // } else if (ac_nonAcRoom.equals("No input provided") || single_doubleBedRoom.equals("No input provided")) {
        //     JOptionPane.showMessageDialog(null, "Select a valid Input!", "Invalid Input", 2);
        // } else if (checkInDate.equals(null) || checkOutDate.equals(null)) {
        //     JOptionPane.showMessageDialog(null, "Please enter a valid Date!", "Invalid Input", 2);
        // } else { // means all values are valid and save them to the database
        //     if (DB.addRoomData(name, email, Integer.parseInt(age), phoneNo, address, roomNo, ac_nonAcRoom, single_doubleBedRoom, mealCombo, checkInDate, checkOutDate)) {
        //         int setRoomStatus = 1; // room status is 1 as it is booked
        //         DB.updateRoomStatus(roomNo, setRoomStatus); // updateRoomStatus in database
        //         AdminRoomsPage page = new AdminRoomsPage(); // reopen admin rooms page
        //         page.setVisible(true);
        //         page.pack();
        //         page.setLocationRelativeTo(null);
        //         this.dispose(); 
        //         adminUtils.changeColour(AdminRoomsPage.roomButton, setRoomStatus);
        //         System.out.println("btn got clicked");
        //         System.out.println("roomNo: " + roomNo);
        //         System.out.println("setRoomStatus: " + setRoomStatus);
        //         System.out.println("roomButton: " + AdminRoomsPage.roomButton);
        //     }
        // }

        AdminRoomsPage page = new AdminRoomsPage();
        page.setVisible(true);
        page.pack();
        page.setLocationRelativeTo(null);
        adminUtils.changeColour(AdminRoomsPage.roomButton, 2);
        System.out.println(AdminRoomsPage.roomButton);
        System.out.println("btn got clicked");

    }//GEN-LAST:event_bookRoomBtnActionPerformeds

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_nameFieldFocusGained
        if (nameField.getText().equals("Enter name")) {
            nameField.setText("");
        }
    }// GEN-LAST:event_nameFieldFocusGained

    private void nameFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_nameFieldFocusLost
        if (nameField.getText().equals("") || nameField.getText().equals("Enter name")) {
            nameField.setText("Enter name");
        }
    }// GEN-LAST:event_nameFieldFocusLost

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_emailFieldFocusGained
        if (emailField.getText().equals("Enter email ID")) {
            emailField.setText("");
        }
    }// GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_emailFieldFocusLost
        if (emailField.getText().equals("") || emailField.getText().equals("Enter email ID")) {
            emailField.setText("Enter email ID");
        }
    }// GEN-LAST:event_emailFieldFocusLost

    private void ageFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_ageFieldFocusGained
        if (ageField.getText().equals("Enter age")) {
            ageField.setText("");
        }
    }// GEN-LAST:event_ageFieldFocusGained

    private void ageFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_ageFieldFocusLost
        if (ageField.getText().equals("") || ageField.getText().equals("Enter age")) {
            ageField.setText("Enter age");
        }
    }// GEN-LAST:event_ageFieldFocusLost

    private void phoneNoFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_phoneNoFieldFocusGained
        if (phoneNoField.getText().equals("Enter Phone No.")) {
            phoneNoField.setText("");
        }
    }// GEN-LAST:event_phoneNoFieldFocusGained

    private void phoneNoFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_phoneNoFieldFocusLost
        if (phoneNoField.getText().equals("") || phoneNoField.getText().equals("Enter Phone No.")) {
            phoneNoField.setText("Enter Phone No.");
        }
    }// GEN-LAST:event_phoneNoFieldFocusLost

    private void addressFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_addressFieldFocusGained
        if (addressField.getText().equals("Enter address")) {
            addressField.setText("");
        }
    }// GEN-LAST:event_addressFieldFocusGained

    private void addressFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_addressFieldFocusLost
        if (addressField.getText().equals("") || addressField.getText().equals("Enter address")) {
            addressField.setText("Enter address");
        }
    }// GEN-LAST:event_addressFieldFocusLost //

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkInCustomer.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkInCustomer.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkInCustomer.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkInCustomer.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkInCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton acRadioBtn;
    private javax.swing.ButtonGroup ac_nonAcBtnGroup;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton bookRoomBtn;
    private javax.swing.JTextField checkInField;
    private javax.swing.JLabel checkInLabel;
    private javax.swing.JTextField checkOutField;
    private javax.swing.JLabel checkOutLabel;
    private javax.swing.JRadioButton doubleBedRadioBtn;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JRadioButton mealComboRadioBtn;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JRadioButton nonAcRadioBtn;
    private javax.swing.JTextField phoneNoField;
    private javax.swing.JLabel phoneNoLabel;
    private javax.swing.JLabel roomDetailsLabel;
    private javax.swing.JTextField roomNoField;
    private javax.swing.JLabel roomNoLabel;
    private javax.swing.JRadioButton singleBedRadioBtn;
    private javax.swing.ButtonGroup single_doubleBedBtnGroup;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
